CREATE TABLE IF NOT EXISTS JOB_MATCH (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    date_found VARCHAR(255) NOT NULL,
    reference_id VARCHAR(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_job_match_id ON JOB_MATCH(id);

CREATE TABLE IF NOT EXISTS JOB_TARGET (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_job_target_id ON JOB_TARGET(id);
